version: 2
models:
- name: stg_ads_benchmark
  columns:
  - name: channel_type
    data_tests:
    - accepted_values:
        arguments:
          values:
          - paid
          - organic
          - retention
- name: stg_channel_code
  columns:
  - name: channel_code
    data_tests:
    - not_null
    - unique
  - name: channel_type
    data_tests:
    - accepted_values:
        arguments:
          values:
          - paid
          - organic
          - retention
    - not_null
- name: stg_leases_month
  columns:
  - name: leasing_contract_id
    data_tests:
    - not_null
    - unique
- name: stg_sessions
  columns:
  - name: session_id
    data_tests:
    - not_null
    - unique
  - name: user_id
    data_tests:
    - not_null
